apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: security-project
type: Opaque
data:
  # postgres
  POSTGRES_DB: a2V5Y2xvYWs= # keycloak
  POSTGRES_USER: a2V5Y2xvYWs= # keycloak
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: security-project
type: Opaque
data:
  # admin
  KEYCLOAK_ADMIN: YWRtaW4= # admin
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= # admin
  # Database connection
  KC_DB_USERNAME: a2V5Y2xvYWs= # keycloak
  KC_DB_PASSWORD: cGFzc3dvcmQ= # password
