apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: security-project
data:
  # Backend configuration
  PORT: "5001"
  KEYCLOAK_URL: "http://keycloak-service:8080"
  KEYCLOAK_REALM: "bezpieczenstwo_projekt_realm"

  # Frontend configuration - POPRAWIONE dla Keycloak 21+!
  REACT_APP_KEYCLOAK_URL: "http://security-project.local" # Bez portu, przez Ingress
  REACT_APP_KEYCLOAK_REALM: "bezpieczenstwo_projekt_realm" #  realm
  REACT_APP_KEYCLOAK_CLIENT_ID: "frontend-app" #  client ID
  REACT_APP_API_URL: "http://security-project.local/api" # API przez Ingress

  # Keycloak configuration
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-service:5432/keycloak"
  KC_HOSTNAME_STRICT: "false"
  KC_HTTP_ENABLED: "true"
