apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: security-project
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: security-project.local
      http:
        paths:
          # Backend API - musi być przed główną ścieżką /
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5001

          # Keycloak - osobne ścieżki
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080

          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080

          - path: /js
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080

          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080

          # Frontend - musi być na końcu (najniższa priorytet)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

    # Dedykowany host dla Keycloak
    - host: keycloak.security-project.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
